
GET localhost:5050/api/users

POST http://localhost:5050/api/users
Content-Type: application/json

{
  "name": "Tharun",
  "age": 20,
  "email": "gowritharun461@gmail.com",
  "password": "tharun0222"
}

